require("suhan.editor")
require("suhan.plugins")
require("suhan.comment")
require("suhan.treesitter")
require("suhan.remaps")
require("suhan.telescope")
require("suhan.nvim-lsp")
require("suhan.autocomplete")
require("suhan.meta-config")

